### ISSUE TITLE
feat: add protocol http wget

### ISSUE THREAD

**Issue by RodrigoDornelles** [gamelly/gly-engine#63]
similar to the curl protocol, but for the wget command.

 - [X] implement `.toWgetProtocol()` in the `http_util.create_request` #52  #90

**Comment by lnpotter** [comment]
Done [426f37a](https://github.com/gamelly/gly-engine/commit/426f37a7218f3e9152fddd912a71eae777da473f).
I forgot to mention the issue in the commit.
